export const latin = [
	['У яе ёсьць плянэта', 'U jaje jość planeta'],
	['еёёююяя', 'jejojojujujaja'],
	['Вельмі Харошы', 'Vielmi Charošy'],
	['Харошы', 'Charošy'],
	['Я 77-ы', 'Ja 77-y'],
	['Я Фанат', 'Ja Fanat'],
] as const;

export const latinJi = [
	['пры інстытуце', 'pry jinstytucie'],
	['поіць', 'pojić'],
	['верабʼі', 'vierabji'],
	['у ім', 'u jim'],
	['іста', 'jista'],
	['Іншы ў ігрушы', 'Jinšy ŭ jihrušy'],
	// ['яна із мною', 'jana iz mnoju'],
	// ['побач ізь ім', 'pobač iź jim'],
	['церазь ямы', 'cieraź jamy'],
	['ня йснуе Іры', 'nia jsnuje Jiry'],
	['маленькія іклы', 'maleńkija jikły'],
	['бязь зьвесткаў', 'biaź źviestkaŭ'],
	['з імглой', 'z imhłoj'],
	['імгла', 'imhła'],
	['з імною', 'z imnoju'],
	['яна йдзе зь ім паіць коні', 'jana jdzie ź jim pajić koni'],
	['мая інфармацыя', 'maja jinfarmacyja'],
	// ['была ізь Сьвятлом', 'była iź Śviatłom'],
	['Харошы', 'Charošy'],
	['знайшлі ...', 'znajšli ...'],
	['ні слуху ...', 'ni słuchu ...'],
	['пралезьці ...', 'praleźci ...'],
	['>Я ня маю ...', '>Ja nia maju ...'],
	['ext>Я Фанат, ...', 'ext>Ja Fanat, ...'],
	['ісьці забаронена ...', 'iści zabaroniena ...'],
	['сталкеру. І мы', 'stałkieru. I my'],
	['У іх', 'U jich'],
	['цалкам іншы,', 'całkam jinšy,'],
	['вачох іхных', 'vačoch jichnych'],
	['... і іншае', '... i jinšaje'],
	['>Я 032, уцяміў', '>Ja 032, uciamiŭ'],
	['КАІР', 'KAJIR'],
	['. Імаверна', '. Imavierna'],
	['Я Інфарматар', 'Ja Jinfarmatar'],
	['<lia>а</lia>', '<lia>a</lia>'],
	// ['залежыць,\\nяк да', 'zaležyć,\\njak da'],
	// ['сюды,\\nё цікавыя', 'siudy,\\njo cikavyja'],
	['Я 77-ы', 'Ja 77-y'],
	['я і ён', 'ja j jon'],
	['я і ўваліўся', 'ja j uvaliŭsia'],
	['Я і Ўваліўся', 'Ja j Uvaliŭsia'],
	['Я І ЎВАЛІЎСЯ', 'JA J UVALIŬSIA'],
] as const;
