#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

[ -f '.git/commit-pkg' ] || {
  echo '[ERROR] Please, use the following command for committing:'
  echo '$ npx git-commit-pkg'
  exit 1
}

npm run build
npm run test
prettier --write .
git add -A .
