#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

[ -f '.git/commit-pkg' ] || {
	echo '[ERROR] Please, use the following command for committing:'
	echo '$ npx git-commit-pkg'
	exit 1
}

bun run build
bun run test
bun run prettier &
bun run lint &
bun run docs
git add -A .
